version: "2.2"
services:
  db:
    image: mysql:5.5
    environment:
    - MYSQL_ROOT_PASSWORD=progetto
    volumes:
    - "./mysql:/var/lib/mysql"
  www:
    build: .
    volumes:
    - "./php:/var/www/html/"
    ports:
    - 8080:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - 8081:80
    environment:
    - PMA_HPST=db
    - PMA_PORT=3306